### ISSUE TITLE
cmdstanr unconstrain draws format changing

### ISSUE THREAD

**Issue by n-kall** [topipa/iwmm#8]
There's a PR to change the output of `unconstrain_draws` to a draws object (stan-dev/cmdstanr/pull/886) so we can simplify the code below when that gets merged

https://github.com/topipa/iwmm/blob/38bdd3bdecc6e2fff0d8ad1185305b9a62834835/R/moment_match.R#L601-L608

**Comment by topipa** [comment]
Closing as resolved in https://github.com/topipa/iwmm/pull/14.
